var h=class extends Error{constructor(a,b){{var c=[b];let d=a;0<c.length&&(d+=` :: ${JSON.stringify(c)}`);c=d}super(c);this.name=a;this.details=b}},k={debug:0,log:1,warn:2,error:3,silent:4},l=/^((?!chrome|android).)*safari/i.test(navigator.userAgent),m=k.warn,n=k.error;
function p(a,b,c){const d=0===a.indexOf("group")?n:k[a];if(m<=d)if(!c||"groupCollapsed"===a&&l)console[a](...b);else console[a](...["%cworkbox",`background: ${c}; color: white; padding: 2px 0.5em; `+"border-radius: 0.5em;"],...b)}
var q=()=>{m<=n&&console.groupEnd()},r={groupEnd:q,unprefixed:{groupEnd:q}},t=(a,b)=>{r[a]=(...c)=>p(a,c,b);r.unprefixed[a]=(...b)=>p(a,b)},u={debug:"#7f8c8d",log:"#2ecc71",warn:"#f39c12",error:"#c0392b",groupCollapsed:"#3498db"},v=(a)=>a&&"object"===typeof a?a:{handle:a},w=class{constructor(a,b,c){this.handler=v(b);this.match=a;this.method=c||"GET"}},x=class extends w{constructor(a,{whitelist:b=[/./],blacklist:c=[]}={}){super((...a)=>this._match(...a),a);this._whitelist=b;this._blacklist=c}_match({event:a,
url:b}){if("navigate"!==a.request.mode)return!1;let c=b.pathname+b.search;return this._blacklist.some((a)=>a.test(c))?!1:this._whitelist.some((a)=>a.test(c))?!0:!1}},y=class extends w{constructor(a,b,c){super(({url:b})=>{const c=a.exec(b.href);return!c||b.origin!==location.origin&&0!==c.index?null:c.slice(1)},b,c)}},z=class{constructor(){this._routes=new Map}handleRequest(a){let b=new URL(a.request.url);if(b.protocol.startsWith("http")){var c=null,d=null;d=this._findHandlerAndParams(a,b);c=d.handler;
d=d.params;!c&&this._defaultHandler&&(c=this._defaultHandler);if(c){try{var e=c.handle({url:b,event:a,params:d})}catch(f){e=Promise.reject(f)}e&&this._catchHandler&&(e=e.catch((c)=>this._catchHandler.handle({url:b,event:a,err:c})));return e}}}_findHandlerAndParams(a,b){var c=this._routes.get(a.request.method)||[];for(let d of c)if(c=d.match({url:b,event:a})){if(Array.isArray(c)&&0===c.length)c=void 0;else if(c.constructor===Object&&0===Object.keys(c).length||!0===c)c=void 0;return{route:d,params:c,
handler:d.handler}}return{handler:void 0,params:void 0}}setDefaultHandler(a){this._defaultHandler=v(a)}setCatchHandler(a){this._catchHandler=v(a)}registerRoute(a){this._routes.has(a.method)||this._routes.set(a.method,[]);this._routes.get(a.method).push(a)}unregisterRoute(a){if(!this._routes.has(a.method))throw new h("unregister-route-but-not-found-with-method",{method:a.method});let b=this._routes.get(a.method).indexOf(a);if(-1<b)this._routes.get(a.method).splice(b,1);else throw new h("unregister-route-route-not-registered");
}},A={prefix:"workbox",suffix:self.registration.scope,googleAnalytics:"googleAnalytics",precache:"precache",runtime:"runtime"},B=(a)=>[A.prefix,a,A.suffix].filter((a)=>0<a.length).join("-"),C={updateDetails:(a)=>{Object.keys(A).forEach((b)=>{"undefined"!==typeof a[b]&&(A[b]=a[b])})},getGoogleAnalyticsName:(a)=>a||B(A.googleAnalytics),getPrecacheName:(a)=>a||B(A.precache),getRuntimeName:(a)=>a||B(A.runtime)},D=new class extends z{registerRoute(a,b,c="GET"){if("string"===typeof a){let d=new URL(a,location);
a=new w(({url:a})=>a.href===d.href,b,c)}else if(a instanceof RegExp)a=new y(a,b,c);else if("function"===typeof a)a=new w(a,b,c);else if(!(a instanceof w))throw new h("unsupported-route-type",{moduleName:"workbox-routing",className:"DefaultRouter",funcName:"registerRoute",paramName:"capture"});super.registerRoute(a);return a}registerNavigationRoute(a,b={}){let c=C.getPrecacheName(b.cacheName);b=new x(()=>caches.match(a,{cacheName:c}).then((b)=>{if(b)return b;throw Error(`The cache ${c} did not have an entry for `+
`${a}.`);}).catch(()=>fetch(a)),{whitelist:b.whitelist,blacklist:b.blacklist});super.registerRoute(b);return b}},E={CACHE_DID_UPDATE:"cacheDidUpdate",CACHE_WILL_UPDATE:"cacheWillUpdate",CACHED_RESPONSE_WILL_BE_USED:"cachedResponseWillBeUsed",FETCH_DID_FAIL:"fetchDidFail",REQUEST_WILL_FETCH:"requestWillFetch"},F={filter:(a,b)=>a.filter((a)=>b in a)},G=new Set,H=async({cacheName:a,request:b,event:c,matchOptions:d,plugins:e=[]})=>{let f=await (await caches.open(a)).match(b,d);for(let g of e)E.CACHED_RESPONSE_WILL_BE_USED in
g&&(f=await g[E.CACHED_RESPONSE_WILL_BE_USED].call(g,{cacheName:a,request:b,event:c,matchOptions:d,cachedResponse:f}));return f},I=async({request:a,response:b,event:c,plugins:d})=>{let e=!1;for(let f of d)if(E.CACHE_WILL_UPDATE in f&&(e=!0,b=await f[E.CACHE_WILL_UPDATE].call(f,{request:a,response:b,event:c}),!b))break;e||(b=b.ok?b:null);return b?b:null},K={put:async({cacheName:a,request:b,response:c,event:d,plugins:e=[]}={})=>{if(!c)throw a=new URL(b.url,location),a=a.origin===location.origin?a.pathname:
a.href,new h("cache-put-with-no-response",{url:a});if(c=await I({request:b,response:c,event:d,plugins:e})){var f=await caches.open(a);e=F.filter(e,E.CACHE_DID_UPDATE);var g=0<e.length?await H({cacheName:a,request:b}):null;try{await f.put(b,c)}catch(L){throw"QuotaExceededError"===L.name&&await J(),L;}for(let f of e)await f[E.CACHE_DID_UPDATE].call(f,{cacheName:a,request:b,event:d,oldResponse:g,newResponse:c})}},match:H},N={fetch:async({request:a,fetchOptions:b,event:c,plugins:d=[]})=>{if(c&&c.preloadResponse){var e=
await c.preloadResponse;if(e)return e}"string"===typeof a&&(a=new Request(a));e=F.filter(d,E.FETCH_DID_FAIL);const f=0<e.length?a.clone():null;try{for(let b of d)E.REQUEST_WILL_FETCH in b&&(a=await b[E.REQUEST_WILL_FETCH].call(b,{request:a.clone(),event:c}))}catch(g){throw new h("plugin-error-request-will-fetch",{thrownError:g});}d=a.clone();try{return await fetch(a,b)}catch(g){for(let a of e)await a[E.FETCH_DID_FAIL].call(a,{error:g,event:c,originalRequest:f.clone(),request:d.clone()});throw g;}}},
O=class{constructor(a={}){this._cacheName=C.getRuntimeName(a.cacheName);this._plugins=a.plugins||[];this._fetchOptions=a.fetchOptions||null;this._matchOptions=a.matchOptions||null}async handle({event:a}){return this.makeRequest({event:a,request:a.request})}async makeRequest({event:a,request:b}){"string"===typeof b&&(b=new Request(b));let c=await K.match({cacheName:this._cacheName,request:b,event:a,matchOptions:this._matchOptions,plugins:this._plugins}),d;if(!c)try{c=await this._getFromNetwork(b,a)}catch(e){d=
e}if(d)throw d;return c}async _getFromNetwork(a,b){let c=await N.fetch({request:a,event:b,fetchOptions:this._fetchOptions,plugins:this._plugins}),d=c.clone();a=K.put({cacheName:this._cacheName,request:a,response:d,event:b,plugins:this._plugins});if(b)try{b.waitUntil(a)}catch(e){}return c}},P={cacheWillUpdate:({response:a})=>a.ok||0===a.status?a:null},Q=class{constructor(a={}){this._cacheName=C.getRuntimeName(a.cacheName);this._plugins=a.plugins?a.plugins.some((a)=>!!a.cacheWillUpdate)?a.plugins:[P,
...a.plugins]:[P];this._networkTimeoutSeconds=a.networkTimeoutSeconds;this._fetchOptions=a.fetchOptions||null;this._matchOptions=a.matchOptions||null}async handle({event:a}){return this.makeRequest({event:a,request:a.request})}async makeRequest({event:a,request:b}){let c=[];"string"===typeof b&&(b=new Request(b));var d=[];let e;if(this._networkTimeoutSeconds){let {id:f,promise:g}=this._getTimeoutPromise({request:b,event:a,logs:c});e=f;d.push(g)}a=this._getNetworkPromise({timeoutId:e,request:b,event:a,
logs:c});d.push(a);(d=await Promise.race(d))||(d=await a);return d}_getTimeoutPromise({request:a,event:b}){let c;return{promise:new Promise((d)=>{c=setTimeout(async()=>{d(await this._respondFromCache({request:a,event:b}))},1E3*this._networkTimeoutSeconds)}),id:c}}async _getNetworkPromise({timeoutId:a,request:b,event:c}){let d,e;try{e=await N.fetch({request:b,event:c,fetchOptions:this._fetchOptions,plugins:this._plugins})}catch(f){d=f}a&&clearTimeout(a);if(d||!e)e=await this._respondFromCache({request:b,
event:c});else if(a=e.clone(),b=K.put({cacheName:this._cacheName,request:b,response:a,event:c,plugins:this._plugins}),c)try{c.waitUntil(b)}catch(f){}return e}_respondFromCache({event:a,request:b}){return K.match({cacheName:this._cacheName,request:b,event:a,matchOptions:this._matchOptions,plugins:this._plugins})}},R=class{constructor(a={}){this._cacheName=C.getRuntimeName(a.cacheName);this._plugins=a.plugins||[];this._plugins=a.plugins?a.plugins.some((a)=>!!a.cacheWillUpdate)?a.plugins:[P,...a.plugins]:
[P];this._fetchOptions=a.fetchOptions||null;this._matchOptions=a.matchOptions||null}async handle({event:a}){return this.makeRequest({event:a,request:a.request})}async makeRequest({event:a,request:b}){"string"===typeof b&&(b=new Request(b));let c=this._getFromNetwork({request:b,event:a});if(b=await K.match({cacheName:this._cacheName,request:b,event:a,matchOptions:this._matchOptions,plugins:this._plugins})){if(a)try{a.waitUntil(c)}catch(d){}}else b=await c;return b}async _getFromNetwork({request:a,
event:b}){let c=await N.fetch({request:a,event:b,fetchOptions:this._fetchOptions,plugins:this._plugins});a=K.put({cacheName:this._cacheName,request:a,response:c.clone(),event:b,plugins:this._plugins});if(b)try{b.waitUntil(a)}catch(d){}return c}},S={cacheFirst:O,cacheOnly:class{constructor(a={}){this._cacheName=C.getRuntimeName(a.cacheName);this._plugins=a.plugins||[];this._matchOptions=a.matchOptions||null}async handle({event:a}){return this.makeRequest({event:a,request:a.request})}async makeRequest({event:a,
request:b}){"string"===typeof b&&(b=new Request(b));return await K.match({cacheName:this._cacheName,request:b,event:a,matchOptions:this._matchOptions,plugins:this._plugins})}},networkFirst:Q,networkOnly:class{constructor(a={}){this._cacheName=C.getRuntimeName(a.cacheName);this._plugins=a.plugins||[];this._fetchOptions=a.fetchOptions||null}async handle({event:a}){return this.makeRequest({event:a,request:a.request})}async makeRequest({event:a,request:b}){"string"===typeof b&&(b=new Request(b));let c,
d;try{d=await N.fetch({request:b,event:a,fetchOptions:this._fetchOptions,plugins:this._plugins})}catch(e){c=e}if(c)throw c;return d}},staleWhileRevalidate:R},T=class{constructor(a,b,{onupgradeneeded:c,onversionchange:d=this._onversionchange}={}){this._name=a;this._version=b;this._onupgradeneeded=c;this._onversionchange=d;this._db=null}async open(){if(!this._db)return this._db=await new Promise((a,b)=>{let c=!1;setTimeout(()=>{c=!0;b(Error("The open request was blocked and timed out"))},this.OPEN_TIMEOUT);
let d=indexedDB.open(this._name,this._version);d.onerror=()=>b(d.error);d.onupgradeneeded=(a)=>{c?(d.transaction.abort(),a.target.result.close()):this._onupgradeneeded&&this._onupgradeneeded(a)};d.onsuccess=(b)=>{b=b.target.result;c?b.close():(b.onversionchange=this._onversionchange,a(b))}}),this}async get(a,...b){return await this._call("get",a,"readonly",...b)}async add(a,...b){return await this._call("add",a,"readwrite",...b)}async put(a,...b){return await this._call("put",a,"readwrite",...b)}async delete(a,
...b){await this._call("delete",a,"readwrite",...b)}async deleteDatabase(){this.close();this._db=null;await new Promise((a,b)=>{let c=indexedDB.deleteDatabase(this._name);c.onerror=(a)=>b(a.target.error);c.onblocked=()=>b(Error("Deletion was blocked."));c.onsuccess=()=>a()})}async getAll(a,b,c){return"getAll"in IDBObjectStore.prototype?await this._call("getAll",a,"readonly",b,c):await this.getAllMatching(a,{query:b,count:c})}async getAllMatching(a,b={}){return await this.transaction([a],"readonly",
(c,d)=>{c=c[a];let e=[];(b.index?c.index(b.index):c).openCursor(b.query||null,b.direction||"next").onsuccess=(a)=>{if(a=a.target.result){var {primaryKey:c,key:f,value:M}=a;e.push(b.includeKeys?{primaryKey:c,key:f,value:M}:M);b.count&&e.length>=b.count?d(e):a.continue()}else d(e)}})}async transaction(a,b,c){await this.open();return await new Promise((d,e)=>{const f=this._db.transaction(a,b);f.onerror=(a)=>e(a.target.error);f.onabort=(a)=>e(a.target.error);f.oncomplete=()=>d();const g={};for(const b of a)g[b]=
f.objectStore(b);c(g,(a)=>d(a),()=>{e(Error("The transaction was manually aborted"));f.abort()})})}async _call(a,b,c,...d){await this.open();return await this.transaction([b],c,(c,f)=>{c[b][a](...d).onsuccess=(a)=>{f(a.target.result)}})}_onversionchange(){this.close()}close(){this._db&&this._db.close()}},U=class{constructor(a){this._storeName=this._cacheName=a;this._db=new T(this._cacheName,2,{onupgradeneeded:(a)=>this._handleUpgrade(a)})}_handleUpgrade(a){let b=a.target.result;2>a.oldVersion&&b.objectStoreNames.contains("workbox-cache-expiration")&&
b.deleteObjectStore("workbox-cache-expiration");b.createObjectStore(this._storeName,{keyPath:"url"}).createIndex("timestamp","timestamp",{unique:!1})}async setTimestamp(a,b){await this._db.put(this._storeName,{url:(new URL(a,location)).href,timestamp:b})}async getAllTimestamps(){return await this._db.getAllMatching(this._storeName,{index:"timestamp"})}async getTimestamp(a){return(await this._db.get(this._storeName,a)).timestamp}async deleteUrl(a){await this._db.delete(this._storeName,(new URL(a,
location)).href)}async delete(){await this._db.deleteDatabase();this._db=null}},aa=class{constructor(a,b={}){this._rerunRequested=this._isRunning=!1;this._maxEntries=b.maxEntries;this._maxAgeSeconds=b.maxAgeSeconds;this._cacheName=a;this._timestampModel=new U(a)}async expireEntries(){if(this._isRunning)this._rerunRequested=!0;else{this._isRunning=!0;var a=Date.now();a=await this._findOldEntries(a);var b=await this._findExtraEntries();a=[...new Set(a.concat(b))];await Promise.all([this._deleteFromCache(a),
this._deleteFromIDB(a)]);this._isRunning=!1;this._rerunRequested&&(this._rerunRequested=!1,this.expireEntries())}}async _findOldEntries(a){if(!this._maxAgeSeconds)return[];let b=a-1E3*this._maxAgeSeconds,c=[];(await this._timestampModel.getAllTimestamps()).forEach((a)=>{a.timestamp<b&&c.push(a.url)});return c}async _findExtraEntries(){let a=[];if(!this._maxEntries)return[];let b=await this._timestampModel.getAllTimestamps();for(;b.length>this._maxEntries;){let c=b.shift();a.push(c.url)}return a}async _deleteFromCache(a){let b=
await caches.open(this._cacheName);for(let c of a)await b.delete(c)}async _deleteFromIDB(a){for(let b of a)await this._timestampModel.deleteUrl(b)}async updateTimestamp(a){a=new URL(a,location);a.hash="";await this._timestampModel.setTimestamp(a.href,Date.now())}async isURLExpired(a){if(!this._maxAgeSeconds)throw new h("expired-test-without-max-age",{methodName:"isURLExpired",paramName:"maxAgeSeconds"});a=new URL(a,location);a.hash="";a=await this._timestampModel.getTimestamp(a.href);let b=Date.now()-
1E3*this._maxAgeSeconds;return a<b}async delete(){this._rerunRequested=!1;await this._timestampModel.delete()}},ba=class{constructor(){try{self.workbox.v=self.workbox.v||{}}catch(a){}}get cacheNames(){return{googleAnalytics:C.getGoogleAnalyticsName(),precache:C.getPrecacheName(),runtime:C.getRuntimeName()}}setCacheNameDetails(a){C.updateDetails(a)}get logLevel(){return m}setLogLevel(a){if(a>k.silent||a<k.debug)throw new h("invalid-value",{paramName:"logLevel",validValueDescription:"Please use a value from LOG_LEVELS, i.e 'logLevel = workbox.core.LOG_LEVELS.debug'.",
value:a});m=a}},Plugin=class{constructor(a={}){this._config=a;this._maxAgeSeconds=a.maxAgeSeconds;this._cacheExpirations=new Map;a.purgeOnQuotaError&&G.add(()=>this.deleteCacheAndMetadata())}_getCacheExpiration(a){if(a===C.getRuntimeName())throw new h("expire-custom-caches-only");let b=this._cacheExpirations.get(a);b||(b=new aa(a,this._config),this._cacheExpirations.set(a,b));return b}cachedResponseWillBeUsed({cacheName:a,cachedResponse:b}){if(!b)return null;let c=this._isResponseDateFresh(b);this._getCacheExpiration(a).expireEntries();
return c?b:null}_isResponseDateFresh(a){if(!this._maxAgeSeconds)return!0;a=this._getDateHeaderTimestamp(a);if(null===a)return!0;let b=Date.now();return a>=b-1E3*this._maxAgeSeconds}_getDateHeaderTimestamp(a){if(!a.headers.has("date"))return null;a=a.headers.get("date");a=(new Date(a)).getTime();return isNaN(a)?null:a}async cacheDidUpdate({cacheName:a,request:b}){a=this._getCacheExpiration(a);await a.updateTimestamp(b.url);await a.expireEntries()}async deleteCacheAndMetadata(){for(let [a,b]of this._cacheExpirations)await caches.delete(a),
await b.delete();this._cacheExpirations=new Map}},V=/^https:\/\/cdn.ampproject.org\/rtv\/\d*\//,W=/^https:\/\/cdn.ampproject.org\/\w*(-\w*)?.js/,X=/^https:\/\/cdn.ampproject.org\/v0\//,Y=class extends Plugin{constructor(a){super(a)}async cacheWillUpdate({response:a}){let b=a.clone(),c=b.headers.get("content-type");if(c&&c.includes("text/html"))try{let c=await b.text();if(/<html (\u26a1|amphtml)/.test(c))return a}catch(d){}return null}},ca=class extends x{constructor(a,{whitelist:b,blacklist:c}={whitelist:[/./],
blacklist:[]}){super(a,{whitelist:b,blacklist:c})}addDeniedUrls(a){this._blacklist.push(a)}removeDeniedUrls(a){this._blacklist=this._blacklist.filter((b)=>b.toString()!==a.toString())}},da=class extends Plugin{constructor(a,b){super(a);this.denyList_=b}async cacheWillUpdate({request:a,response:b}){var c=null;this.denyList_&&this.denyList_.forEach((b)=>{if(b.test(a.url))return null});c=super.cacheWillUpdate?await super.cacheWillUpdate({response:b}):b;if(!c)return null;b=c.clone();return(c=b.headers.get("content-type"))&&
c.includes("text/html")?null:b}},Z=[{regexp:/https:\/\/fonts\.googleapis\.com\/.*/,cachingStrategy:"STALE_WHILE_REVALIDATE"},{regexp:/https:\/\/cdn\.ampproject\.org\/.*/,cachingStrategy:"STALE_WHILE_REVALIDATE"}];ea({});try{self.workbox.v["workbox:core:3.6.2"]=1}catch(a){}Object.keys(u).forEach((a)=>t(a,u[a]));try{self.workbox.v["workbox:routing:3.6.2"]=1}catch(a){}self.addEventListener("fetch",(a)=>{let b=D.handleRequest(a);b&&a.respondWith(b)});async function J(){for(let a of G)await a()}
try{self.workbox.v["workbox:strategies:3.6.2"]=1}catch(a){}Object.keys(S).forEach(()=>{});try{self.workbox.v["workbox:cache-expiration:3.6.2"]=1}catch(a){}T.prototype.OPEN_TIMEOUT=2E3;new ba;async function fa(a){let b=[],c=[];a.forEach((a)=>{X.test(a)||W.test(a)?b.push(new Request(a)):V.test(a)&&c.push(new Request(a))});await (await caches.open("AMP-UNVERSIONED-CACHE")).addAll(b);await (await caches.open("AMP-VERSIONED-CACHE")).addAll(c)}try{self.workbox.v["workbox:navigation-preload:3.6.2"]=1}catch(a){}
function ha(a){self.registration&&self.registration.navigationPreload&&self.addEventListener("activate",(b)=>{b.waitUntil(self.registration.navigationPreload.enable().then(()=>{a&&self.registration.navigationPreload.setHeaderValue(a)}))})}
function ea(a={maxDocumentsInCache:10,maxAgeSecondsforDocumentsInCache:432E3,timeoutSeconds:3}){ha();let b={};a.allowList?b.whitelist=a.allowList:a.denyList&&(b.blacklist=a.denyList);a.timeoutSeconds&&5<a.timeoutSeconds&&(a.timeoutSeconds=5);a.maxDocumentsInCache&&10<a.maxDocumentsInCache&&(a.maxDocumentsInCache=10);a=new ca(new Q({cacheName:"AMP-PUBLISHER-CACHE",plugins:[new Y({maxEntries:a.maxDocumentsInCache||10,maxAgeSeconds:a.maxAgeSecondsforDocumentsInCache||432E3})],networkTimeoutSeconds:a.timeoutSeconds}),
b);D.registerRoute(a);return a}function ia(a){return a.map(async(a)=>{if(a&&a.url)try{let b=new Request(a.url,{mode:"same-origin"}),d=await fetch(b),e=await (new Y({maxEntries:10})).cacheWillUpdate({response:d}),f=await caches.open("AMP-PUBLISHER-CACHE");e&&f.put(b,e)}catch(c){}})}
function ja(a){a.forEach((a)=>{var b={cacheName:"AMP-ASSET-CACHE",plugins:[new da({maxEntries:25,denyList:a.denyList})]};switch(a.cachingStrategy){case "NETWORK_FIRST":b=new Q(b);break;case "STALE_WHILE_REVALIDATE":b=new R(b);break;default:b=new O(b)}D.registerRoute(a.regexp,b)})}D.registerRoute(V,new O({cacheName:"AMP-VERSIONED-CACHE",plugins:[new Plugin({maxAgeSeconds:1209600})]}));D.registerRoute(W,new R({cacheName:"AMP-UNVERSIONED-CACHE",plugins:[new Plugin({maxAgeSeconds:86400})]}));
D.registerRoute(X,new R({cacheName:"AMP-UNVERSIONED-CACHE",plugins:[new Plugin({maxAgeSeconds:86400})]}));self.addEventListener("message",(a)=>{let b=JSON.parse(a.data);"AMP__FIRST-VISIT-CACHING"===b.type&&b.payload&&a.waitUntil(fa(b.payload))});Z&&0<Z.length&&ja(Z);self.addEventListener("install",function(a){let {skipWaiting:b}=self;a.waitUntil(b())});self.addEventListener("activate",async(a)=>{let {clients:b}=self;a.waitUntil(b.claim().then(async()=>{let a=await b.matchAll({type:"window"});return Promise.all(ia(a))}))});
