import gulp from 'gulp';
import del from 'del';

import settings from '~/setup/settings.js';

/**
 * Removes files that may be regenerated by the following tasks
 */
export default function clean() {
    return del(settings.clean.src)
}
