import gulp from 'gulp';
import rm from 'gulp-rm';

import settings from '~/setup/settings.js';

/**
 * Removes files that may be regenerated by the following tasks
 */
export default function clean(done) {
    let stream = gulp.src(settings.clean.src, {'read': false});

    stream.pipe(rm({'async': false}));

    done();
}
