const US_CAPITAL_CITIES = [
  'Montgomery, Alabama',
  'Juneau, Alaska',
  'Phoenix, Arizona',
  'Little Rock, Arkansas',
  'Sacramento, California',
  'Denver, Colorado',
  'Hartford, Connecticut',
  'Dover, Delaware',
  'Tallahassee, Florida',
  'Atlanta, Georgia',
  'Honolulu, Hawaii',
  'Boise, Idaho',
  'Springfield, Illinois',
  'Indianapolis, Indiana',
  'Des Moines, Iowa',
  'Topeka, Kansas',
  'Frankfort, Kentucky',
  'Baton Rouge, Louisiana',
  'Augusta, Maine',
  'Annapolis, Maryland',
  'Boston, Massachusetts',
  'Lansing, Michigan',
  'Saint Paul, Minnesota',
  'Jackson, Mississippi',
  'Jefferson City, Missouri',
  'Helena, Montana',
  'Lincoln, Nebraska',
  'Carson City, Nevada',
  'Concord, New Hampshire',
  'Trenton, New Jersey',
  'Santa Fe, New Mexico',
  'Albany, New York',
  'Raleigh, North Carolina',
  'Bismarck, North Dakota',
  'Columbus, Ohio',
  'Oklahoma City, Oklahoma',
  'Salem, Oregon',
  'Harrisburg, Pennsylvania',
  'Providence, Rhode Island',
  'Columbia, South Carolina',
  'Pierre, South Dakota',
  'Nashville, Tennessee',
  'Austin, Texas',
  'Salt Lake City, Utah',
  'Montpelier, Vermont',
  'Richmond, Virginia',
  'Olympia, Washington',
  'Charleston, West Virginia',
  'Madison, Wisconsin',
  'Cheyenne, Wyoming',
];
const US_CAPITAL_CITIES_RICH = [
  {
    'city': 'Albany',
    'state': 'New York',
    'areaCode': 518,
    'population': 98251,
  },
  {
    'city': 'Annapolis',
    'state': 'Maryland',
    'areaCode': 410,
    'population': 39321,
  },
  {
    'city': 'Trenton',
    'state': 'New Jersey',
    'areaCode': 609,
    'population': 84964,
  },
];
const CHARACTERS = [
  {'email': 'harrypotter@hogwarts.edu', 'name': 'Harry Potter'},
  {
    'email': 'albusdumbledore@hogwarts.edu',
    'name': 'Albus Dumbledore',
  },
  {
    'email': 'voldemort@deatheater.org',
    'name': 'Tom Marvolo Riddle',
  },
  {'email': 'severussnape@hogwarts.edu', 'name': 'Severus Snape'},
  {'email': 'siriusblack@hogwarts.edu', 'name': 'Sirius Black'},
  {
    'email': 'hermionegranger@hogwarts.edu',
    'name': 'Hermione Granger',
  },
  {'email': 'ronweasley@hogwarts.edu', 'name': 'Ron Weasley'},
  {'email': 'dracomalfoy@hogwarts.edu', 'name': 'Draco Malfoy'},
  {
    'email': 'nevillelongbottom@hogwarts.edu',
    'name': 'Neville Longbottom',
  },
  {'email': 'rubeushagrid@hogwarts.edu', 'name': 'Rubeus Hagrid'},
  {'email': 'dobby@hogwarts.edu', 'name': 'Dobby'},
  {
    'email': 'bellatrixlestrange@deatheater.org',
    'name': 'Bellatrix Lestrange',
  },
  {
    'email': 'minervamcgonagall@hogwarts.edu',
    'name': 'Minerva McGonagall',
  },
];

module.exports = {
  CHARACTERS,
  US_CAPITAL_CITIES,
  US_CAPITAL_CITIES_RICH,
};
